services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [mongo-data:/data/db]
  api:
    build: ./backend/Quan4CulinaryTourism.Api
    depends_on: [mongo]
    ports: ["5163:8080"]
    env_file:
      - ./backend/Quan4CulinaryTourism.Api/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDbSettings__ConnectionString: mongodb://mongo:27017
volumes:
  mongo-data:
